/**
 * Major cities worldwide for autocomplete.
 * Format: "City, State, USA" (US cities) or "City, Country" (international).
 */

export const CITIES: string[] = [
  // ─── United States (100+) ───────────────────────────────────────────
  "New York, NY, USA",
  "Los Angeles, CA, USA",
  "Chicago, IL, USA",
  "Houston, TX, USA",
  "Phoenix, AZ, USA",
  "Philadelphia, PA, USA",
  "San Antonio, TX, USA",
  "San Diego, CA, USA",
  "Dallas, TX, USA",
  "San Jose, CA, USA",
  "Austin, TX, USA",
  "Jacksonville, FL, USA",
  "Fort Worth, TX, USA",
  "Columbus, OH, USA",
  "Charlotte, NC, USA",
  "Indianapolis, IN, USA",
  "San Francisco, CA, USA",
  "Seattle, WA, USA",
  "Denver, CO, USA",
  "Nashville, TN, USA",
  "Washington, DC, USA",
  "Oklahoma City, OK, USA",
  "El Paso, TX, USA",
  "Boston, MA, USA",
  "Portland, OR, USA",
  "Las Vegas, NV, USA",
  "Memphis, TN, USA",
  "Louisville, KY, USA",
  "Baltimore, MD, USA",
  "Milwaukee, WI, USA",
  "Albuquerque, NM, USA",
  "Tucson, AZ, USA",
  "Fresno, CA, USA",
  "Mesa, AZ, USA",
  "Sacramento, CA, USA",
  "Atlanta, GA, USA",
  "Kansas City, MO, USA",
  "Colorado Springs, CO, USA",
  "Omaha, NE, USA",
  "Raleigh, NC, USA",
  "Long Beach, CA, USA",
  "Virginia Beach, VA, USA",
  "Miami, FL, USA",
  "Oakland, CA, USA",
  "Minneapolis, MN, USA",
  "Tampa, FL, USA",
  "Tulsa, OK, USA",
  "Arlington, TX, USA",
  "New Orleans, LA, USA",
  "Wichita, KS, USA",
  "Cleveland, OH, USA",
  "Bakersfield, CA, USA",
  "Aurora, CO, USA",
  "Anaheim, CA, USA",
  "Honolulu, HI, USA",
  "Santa Ana, CA, USA",
  "Riverside, CA, USA",
  "Corpus Christi, TX, USA",
  "Lexington, KY, USA",
  "Pittsburgh, PA, USA",
  "Anchorage, AK, USA",
  "Stockton, CA, USA",
  "Cincinnati, OH, USA",
  "Saint Paul, MN, USA",
  "Toledo, OH, USA",
  "Newark, NJ, USA",
  "Greensboro, NC, USA",
  "Buffalo, NY, USA",
  "Plano, TX, USA",
  "Lincoln, NE, USA",
  "Henderson, NV, USA",
  "Fort Wayne, IN, USA",
  "Jersey City, NJ, USA",
  "St. Petersburg, FL, USA",
  "Chula Vista, CA, USA",
  "Norfolk, VA, USA",
  "Orlando, FL, USA",
  "Chandler, AZ, USA",
  "Laredo, TX, USA",
  "Madison, WI, USA",
  "Durham, NC, USA",
  "Lubbock, TX, USA",
  "Winston-Salem, NC, USA",
  "Garland, TX, USA",
  "Glendale, AZ, USA",
  "Hialeah, FL, USA",
  "Reno, NV, USA",
  "Baton Rouge, LA, USA",
  "Irvine, CA, USA",
  "Chesapeake, VA, USA",
  "Irving, TX, USA",
  "Scottsdale, AZ, USA",
  "North Las Vegas, NV, USA",
  "Fremont, CA, USA",
  "Gilbert, AZ, USA",
  "San Bernardino, CA, USA",
  "Boise, ID, USA",
  "Birmingham, AL, USA",
  "Rochester, NY, USA",
  "Richmond, VA, USA",
  "Spokane, WA, USA",
  "Des Moines, IA, USA",
  "Montgomery, AL, USA",
  "Modesto, CA, USA",
  "Fayetteville, NC, USA",
  "Tacoma, WA, USA",
  "Shreveport, LA, USA",
  "Fontana, CA, USA",
  "Moreno Valley, CA, USA",
  "Akron, OH, USA",
  "Yonkers, NY, USA",
  "Salt Lake City, UT, USA",
  "Huntsville, AL, USA",
  "Savannah, GA, USA",
  "Charleston, SC, USA",
  "Providence, RI, USA",
  "Hartford, CT, USA",
  "Little Rock, AR, USA",
  "Knoxville, TN, USA",
  "Chattanooga, TN, USA",
  "Provo, UT, USA",
  "Ann Arbor, MI, USA",
  "Detroit, MI, USA",
  "Grand Rapids, MI, USA",

  // ─── Canada (50+) ──────────────────────────────────────────────────
  "Toronto, Canada",
  "Montreal, Canada",
  "Vancouver, Canada",
  "Calgary, Canada",
  "Edmonton, Canada",
  "Ottawa, Canada",
  "Winnipeg, Canada",
  "Quebec City, Canada",
  "Hamilton, Canada",
  "Kitchener, Canada",
  "London, Canada",
  "Victoria, Canada",
  "Halifax, Canada",
  "Oshawa, Canada",
  "Windsor, Canada",
  "Saskatoon, Canada",
  "Regina, Canada",
  "St. John's, Canada",
  "Barrie, Canada",
  "Kelowna, Canada",
  "Abbotsford, Canada",
  "Sudbury, Canada",
  "Kingston, Canada",
  "Sherbrooke, Canada",
  "Trois-Rivieres, Canada",
  "Guelph, Canada",
  "Moncton, Canada",
  "Brantford, Canada",
  "Thunder Bay, Canada",
  "Saint John, Canada",
  "Peterborough, Canada",
  "Nanaimo, Canada",
  "Lethbridge, Canada",
  "Kamloops, Canada",
  "Red Deer, Canada",
  "Prince George, Canada",
  "Medicine Hat, Canada",
  "Drummondville, Canada",
  "Granby, Canada",
  "Fredericton, Canada",
  "Charlottetown, Canada",
  "Chilliwack, Canada",
  "Belleville, Canada",
  "Sarnia, Canada",
  "Chatham-Kent, Canada",
  "Airdrie, Canada",
  "Courtenay, Canada",
  "North Bay, Canada",
  "Brampton, Canada",
  "Mississauga, Canada",
  "Markham, Canada",
  "Surrey, Canada",
  "Burnaby, Canada",
  "Richmond, Canada",
  "Laval, Canada",

  // ─── Europe (50+) ──────────────────────────────────────────────────
  "London, United Kingdom",
  "Paris, France",
  "Berlin, Germany",
  "Madrid, Spain",
  "Rome, Italy",
  "Amsterdam, Netherlands",
  "Barcelona, Spain",
  "Vienna, Austria",
  "Munich, Germany",
  "Milan, Italy",
  "Prague, Czech Republic",
  "Dublin, Ireland",
  "Brussels, Belgium",
  "Stockholm, Sweden",
  "Lisbon, Portugal",
  "Copenhagen, Denmark",
  "Oslo, Norway",
  "Helsinki, Finland",
  "Warsaw, Poland",
  "Budapest, Hungary",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Edinburgh, United Kingdom",
  "Manchester, United Kingdom",
  "Birmingham, United Kingdom",
  "Hamburg, Germany",
  "Frankfurt, Germany",
  "Lyon, France",
  "Marseille, France",
  "Naples, Italy",
  "Turin, Italy",
  "Valencia, Spain",
  "Seville, Spain",
  "Krakow, Poland",
  "Bucharest, Romania",
  "Sofia, Bulgaria",
  "Athens, Greece",
  "Thessaloniki, Greece",
  "Zagreb, Croatia",
  "Belgrade, Serbia",
  "Bratislava, Slovakia",
  "Ljubljana, Slovenia",
  "Vilnius, Lithuania",
  "Riga, Latvia",
  "Tallinn, Estonia",
  "Cologne, Germany",
  "Dusseldorf, Germany",
  "Stuttgart, Germany",
  "Rotterdam, Netherlands",
  "Antwerp, Belgium",
  "Porto, Portugal",
  "Nice, France",
  "Toulouse, France",
  "Glasgow, United Kingdom",
  "Leeds, United Kingdom",
  "Bristol, United Kingdom",

  // ─── Asia (50+) ────────────────────────────────────────────────────
  "Tokyo, Japan",
  "Singapore, Singapore",
  "Bangalore, India",
  "Mumbai, India",
  "Shanghai, China",
  "Beijing, China",
  "Seoul, South Korea",
  "Hong Kong, China",
  "Delhi, India",
  "Bangkok, Thailand",
  "Taipei, Taiwan",
  "Osaka, Japan",
  "Kuala Lumpur, Malaysia",
  "Jakarta, Indonesia",
  "Manila, Philippines",
  "Shenzhen, China",
  "Guangzhou, China",
  "Hyderabad, India",
  "Chennai, India",
  "Pune, India",
  "Kolkata, India",
  "Ahmedabad, India",
  "Hanoi, Vietnam",
  "Ho Chi Minh City, Vietnam",
  "Chengdu, China",
  "Hangzhou, China",
  "Nanjing, China",
  "Wuhan, China",
  "Suzhou, China",
  "Busan, South Korea",
  "Kyoto, Japan",
  "Nagoya, Japan",
  "Fukuoka, Japan",
  "Yokohama, Japan",
  "Dhaka, Bangladesh",
  "Islamabad, Pakistan",
  "Karachi, Pakistan",
  "Lahore, Pakistan",
  "Colombo, Sri Lanka",
  "Kathmandu, Nepal",
  "Phnom Penh, Cambodia",
  "Yangon, Myanmar",
  "Surat, India",
  "Jaipur, India",
  "Lucknow, India",
  "Kanpur, India",
  "Nagpur, India",
  "Indore, India",
  "Cebu City, Philippines",
  "Davao City, Philippines",
  "Surabaya, Indonesia",
  "Bandung, Indonesia",
  "Penang, Malaysia",
  "Johor Bahru, Malaysia",

  // ─── Middle East (15+) ─────────────────────────────────────────────
  "Dubai, UAE",
  "Abu Dhabi, UAE",
  "Tel Aviv, Israel",
  "Jerusalem, Israel",
  "Riyadh, Saudi Arabia",
  "Jeddah, Saudi Arabia",
  "Doha, Qatar",
  "Kuwait City, Kuwait",
  "Muscat, Oman",
  "Manama, Bahrain",
  "Amman, Jordan",
  "Beirut, Lebanon",
  "Istanbul, Turkey",
  "Ankara, Turkey",
  "Izmir, Turkey",
  "Tehran, Iran",

  // ─── Australia & New Zealand (15+) ─────────────────────────────────
  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Perth, Australia",
  "Adelaide, Australia",
  "Canberra, Australia",
  "Gold Coast, Australia",
  "Hobart, Australia",
  "Darwin, Australia",
  "Newcastle, Australia",
  "Wollongong, Australia",
  "Cairns, Australia",
  "Townsville, Australia",
  "Auckland, New Zealand",
  "Wellington, New Zealand",
  "Christchurch, New Zealand",
  "Hamilton, New Zealand",

  // ─── Latin America (25+) ───────────────────────────────────────────
  "Mexico City, Mexico",
  "Sao Paulo, Brazil",
  "Buenos Aires, Argentina",
  "Rio de Janeiro, Brazil",
  "Bogota, Colombia",
  "Lima, Peru",
  "Santiago, Chile",
  "Guadalajara, Mexico",
  "Monterrey, Mexico",
  "Medellin, Colombia",
  "Brasilia, Brazil",
  "Curitiba, Brazil",
  "Belo Horizonte, Brazil",
  "Porto Alegre, Brazil",
  "Recife, Brazil",
  "Salvador, Brazil",
  "Fortaleza, Brazil",
  "Quito, Ecuador",
  "Guayaquil, Ecuador",
  "Caracas, Venezuela",
  "Montevideo, Uruguay",
  "Asuncion, Paraguay",
  "La Paz, Bolivia",
  "San Jose, Costa Rica",
  "Panama City, Panama",
  "Havana, Cuba",
  "Santo Domingo, Dominican Republic",
  "Guatemala City, Guatemala",
  "Tegucigalpa, Honduras",
  "San Salvador, El Salvador",

  // ─── Africa (20+) ──────────────────────────────────────────────────
  "Lagos, Nigeria",
  "Cairo, Egypt",
  "Johannesburg, South Africa",
  "Cape Town, South Africa",
  "Nairobi, Kenya",
  "Casablanca, Morocco",
  "Accra, Ghana",
  "Addis Ababa, Ethiopia",
  "Dar es Salaam, Tanzania",
  "Kampala, Uganda",
  "Abuja, Nigeria",
  "Durban, South Africa",
  "Pretoria, South Africa",
  "Algiers, Algeria",
  "Tunis, Tunisia",
  "Dakar, Senegal",
  "Luanda, Angola",
  "Maputo, Mozambique",
  "Kigali, Rwanda",
  "Lusaka, Zambia",
  "Harare, Zimbabwe",
  "Windhoek, Namibia",
  "Gaborone, Botswana",

  // ─── Remote / Special ──────────────────────────────────────────────
  "Remote",
  "Remote, USA",
  "Remote, Canada",
  "Remote, Europe",
  "Remote, Worldwide",
];

/**
 * Common abbreviations and nicknames mapped to their canonical city name.
 */
export const searchTerms: Record<string, string> = {
  sf: "San Francisco, CA, USA",
  nyc: "New York, NY, USA",
  la: "Los Angeles, CA, USA",
  dc: "Washington, DC, USA",
  lv: "Las Vegas, NV, USA",
  atl: "Atlanta, GA, USA",
  chi: "Chicago, IL, USA",
  phx: "Phoenix, AZ, USA",
  philly: "Philadelphia, PA, USA",
  nola: "New Orleans, LA, USA",
  slc: "Salt Lake City, UT, USA",
  kc: "Kansas City, MO, USA",
  okc: "Oklahoma City, OK, USA",
  dtw: "Detroit, MI, USA",
  jax: "Jacksonville, FL, USA",
  htown: "Houston, TX, USA",
  dfw: "Dallas, TX, USA",
  bos: "Boston, MA, USA",
  pdx: "Portland, OR, USA",
  sea: "Seattle, WA, USA",
  den: "Denver, CO, USA",
  msp: "Minneapolis, MN, USA",
  stl: "St. Louis, MO, USA",
  clt: "Charlotte, NC, USA",
  rdu: "Raleigh, NC, USA",
  sac: "Sacramento, CA, USA",
  yvr: "Vancouver, Canada",
  yyz: "Toronto, Canada",
  yul: "Montreal, Canada",
  mel: "Melbourne, Australia",
  syd: "Sydney, Australia",
  hk: "Hong Kong, China",
  bkk: "Bangkok, Thailand",
  kl: "Kuala Lumpur, Malaysia",
  sg: "Singapore, Singapore",
};

/**
 * Filter cities for autocomplete suggestions.
 *
 * 1. Returns [] if query is fewer than 2 characters.
 * 2. Checks searchTerms for an exact abbreviation match (case-insensitive).
 * 3. Filters CITIES where the query matches any part (case-insensitive).
 * 4. Returns top 10, prioritizing cities whose name STARTS with the query.
 */
export function filterCities(query: string): string[] {
  const trimmed = query.trim();
  if (trimmed.length < 2) {
    return [];
  }

  const lower = trimmed.toLowerCase();

  // Check abbreviation map first
  const abbreviated = searchTerms[lower];
  if (abbreviated) {
    // Return the abbreviated match at the top, plus other partial matches
    const others = CITIES.filter(
      (c) => c !== abbreviated && c.toLowerCase().includes(lower)
    );
    return [abbreviated, ...others].slice(0, 10);
  }

  // Split into starts-with vs. contains for priority ordering
  const startsWith: string[] = [];
  const contains: string[] = [];

  for (const city of CITIES) {
    const cityLower = city.toLowerCase();
    if (cityLower.startsWith(lower)) {
      startsWith.push(city);
    } else if (cityLower.includes(lower)) {
      contains.push(city);
    }
  }

  return [...startsWith, ...contains].slice(0, 10);
}
