const _RAW_JOB_TITLES: string[] = [
  // ── Engineering ──────────────────────────────────────────────────────
  // Software Engineering
  "Junior Software Engineer",
  "Mid-Level Software Engineer",
  "Software Engineer",
  "Senior Software Engineer",
  "Staff Software Engineer",
  "Principal Software Engineer",
  "Lead Software Engineer",
  "Software Development Engineer",
  "Software Architect",
  "Solutions Architect",
  "Enterprise Architect",
  "Technical Architect",

  // Frontend Engineering
  "Junior Frontend Engineer",
  "Frontend Engineer",
  "Senior Frontend Engineer",
  "Staff Frontend Engineer",
  "Lead Frontend Engineer",
  "Frontend Developer",
  "Senior Frontend Developer",
  "UI Engineer",
  "Web Developer",
  "Senior Web Developer",

  // Backend Engineering
  "Junior Backend Engineer",
  "Backend Engineer",
  "Senior Backend Engineer",
  "Staff Backend Engineer",
  "Lead Backend Engineer",
  "Backend Developer",
  "Senior Backend Developer",
  "API Engineer",

  // Full Stack Engineering
  "Junior Full Stack Engineer",
  "Full Stack Engineer",
  "Senior Full Stack Engineer",
  "Staff Full Stack Engineer",
  "Lead Full Stack Engineer",
  "Full Stack Developer",
  "Senior Full Stack Developer",

  // Mobile Engineering
  "Junior Mobile Engineer",
  "Mobile Engineer",
  "Senior Mobile Engineer",
  "Staff Mobile Engineer",
  "Lead Mobile Engineer",
  "Mobile Developer",
  "Senior Mobile Developer",
  "iOS Engineer",
  "Senior iOS Engineer",
  "Lead iOS Engineer",
  "iOS Developer",
  "Android Engineer",
  "Senior Android Engineer",
  "Lead Android Engineer",
  "Android Developer",
  "React Native Developer",
  "Flutter Developer",

  // DevOps & Infrastructure
  "Junior DevOps Engineer",
  "DevOps Engineer",
  "Senior DevOps Engineer",
  "Staff DevOps Engineer",
  "Lead DevOps Engineer",
  "Site Reliability Engineer",
  "Senior Site Reliability Engineer",
  "Staff Site Reliability Engineer",
  "Platform Engineer",
  "Senior Platform Engineer",
  "Staff Platform Engineer",
  "Lead Platform Engineer",
  "Infrastructure Engineer",
  "Senior Infrastructure Engineer",
  "Lead Infrastructure Engineer",
  "Cloud Engineer",
  "Senior Cloud Engineer",
  "Cloud Architect",
  "Cloud Solutions Architect",
  "Release Engineer",
  "Build Engineer",
  "Systems Administrator",
  "Network Engineer",
  "Senior Network Engineer",

  // Security
  "Security Engineer",
  "Senior Security Engineer",
  "Staff Security Engineer",
  "Lead Security Engineer",
  "Application Security Engineer",
  "Cloud Security Engineer",
  "Information Security Analyst",
  "Security Architect",
  "Cybersecurity Analyst",
  "Penetration Tester",

  // QA & Testing
  "QA Engineer",
  "Senior QA Engineer",
  "Lead QA Engineer",
  "QA Analyst",
  "Test Engineer",
  "Senior Test Engineer",
  "SDET",
  "Senior SDET",
  "Automation Engineer",
  "Quality Assurance Manager",
  "Test Lead",

  // Embedded & Systems
  "Embedded Engineer",
  "Senior Embedded Engineer",
  "Embedded Software Engineer",
  "Systems Engineer",
  "Senior Systems Engineer",
  "Firmware Engineer",
  "Senior Firmware Engineer",
  "Hardware Engineer",
  "Robotics Engineer",

  // Data Engineering
  "Junior Data Engineer",
  "Data Engineer",
  "Senior Data Engineer",
  "Staff Data Engineer",
  "Lead Data Engineer",
  "Principal Data Engineer",
  "ETL Developer",
  "Data Platform Engineer",
  "Big Data Engineer",
  "Database Administrator",
  "Database Engineer",
  "Data Architect",

  // ML Engineering
  "Junior ML Engineer",
  "ML Engineer",
  "Senior ML Engineer",
  "Staff ML Engineer",
  "Lead ML Engineer",
  "Principal ML Engineer",
  "Machine Learning Engineer",
  "Senior Machine Learning Engineer",
  "MLOps Engineer",
  "NLP Engineer",
  "Computer Vision Engineer",

  // Other Engineering
  "Blockchain Engineer",
  "Smart Contract Developer",
  "Game Developer",
  "Senior Game Developer",
  "Graphics Engineer",
  "Audio Engineer",
  "Compiler Engineer",
  "Performance Engineer",
  "Reliability Engineer",
  "Integration Engineer",
  "Support Engineer",

  // ── Product ──────────────────────────────────────────────────────────
  "Associate Product Manager",
  "Junior Product Manager",
  "Product Manager",
  "Senior Product Manager",
  "Staff Product Manager",
  "Principal Product Manager",
  "Group Product Manager",
  "Technical Product Manager",
  "Product Owner",
  "Senior Product Owner",
  "Product Analyst",
  "Product Marketing Manager",
  "Product Operations Manager",
  "Director of Product",
  "Senior Director of Product",
  "VP of Product",
  "SVP of Product",
  "Chief Product Officer",

  // ── Design ───────────────────────────────────────────────────────────
  "Junior UX Designer",
  "UX Designer",
  "Senior UX Designer",
  "Lead UX Designer",
  "Junior UI Designer",
  "UI Designer",
  "Senior UI Designer",
  "Lead UI Designer",
  "UX/UI Designer",
  "Senior UX/UI Designer",
  "Junior Product Designer",
  "Product Designer",
  "Senior Product Designer",
  "Staff Product Designer",
  "Principal Product Designer",
  "Design Lead",
  "Design Manager",
  "Design Director",
  "Senior Design Director",
  "VP of Design",
  "Head of Design",
  "UX Researcher",
  "Senior UX Researcher",
  "Lead UX Researcher",
  "UX Research Manager",
  "Visual Designer",
  "Senior Visual Designer",
  "Interaction Designer",
  "Senior Interaction Designer",
  "Brand Designer",
  "Senior Brand Designer",
  "Graphic Designer",
  "Senior Graphic Designer",
  "Motion Designer",
  "Senior Motion Designer",
  "Content Designer",
  "Senior Content Designer",
  "Design Systems Designer",
  "Design Technologist",
  "Creative Director",
  "Art Director",

  // ── Data / ML / AI ───────────────────────────────────────────────────
  "Junior Data Scientist",
  "Data Scientist",
  "Senior Data Scientist",
  "Staff Data Scientist",
  "Lead Data Scientist",
  "Principal Data Scientist",
  "Junior Data Analyst",
  "Data Analyst",
  "Senior Data Analyst",
  "Lead Data Analyst",
  "Junior Business Analyst",
  "Business Analyst",
  "Senior Business Analyst",
  "Lead Business Analyst",
  "Business Intelligence Analyst",
  "Senior Business Intelligence Analyst",
  "BI Developer",
  "AI Engineer",
  "Senior AI Engineer",
  "Lead AI Engineer",
  "AI/ML Researcher",
  "Research Scientist",
  "Senior Research Scientist",
  "Staff Research Scientist",
  "Principal Research Scientist",
  "Applied Scientist",
  "Senior Applied Scientist",
  "Research Engineer",
  "Senior Research Engineer",
  "Analytics Engineer",
  "Senior Analytics Engineer",
  "Lead Analytics Engineer",
  "Quantitative Analyst",
  "Senior Quantitative Analyst",
  "Statistician",
  "Data Visualization Analyst",

  // ── Management & Leadership ──────────────────────────────────────────
  "Engineering Manager",
  "Senior Engineering Manager",
  "Director of Engineering",
  "Senior Director of Engineering",
  "VP of Engineering",
  "SVP of Engineering",
  "CTO",
  "Technical Lead",
  "Senior Technical Lead",
  "Team Lead",
  "Tech Lead Manager",
  "Development Manager",
  "Software Development Manager",
  "IT Manager",
  "IT Director",
  "Project Manager",
  "Senior Project Manager",
  "Technical Project Manager",
  "Program Manager",
  "Senior Program Manager",
  "Technical Program Manager",
  "Senior Technical Program Manager",
  "Principal Technical Program Manager",
  "Scrum Master",
  "Senior Scrum Master",
  "Agile Coach",
  "Delivery Manager",
  "Release Manager",
  "Portfolio Manager",

  // ── Sales ────────────────────────────────────────────────────────────
  "Sales Representative",
  "Senior Sales Representative",
  "Sales Associate",
  "Inside Sales Representative",
  "Outside Sales Representative",
  "Account Executive",
  "Senior Account Executive",
  "Enterprise Account Executive",
  "Strategic Account Executive",
  "Sales Manager",
  "Senior Sales Manager",
  "Regional Sales Manager",
  "Sales Director",
  "Senior Sales Director",
  "VP of Sales",
  "SVP of Sales",
  "Chief Revenue Officer",
  "Account Manager",
  "Senior Account Manager",
  "Key Account Manager",
  "Strategic Account Manager",
  "Business Development Representative",
  "Senior Business Development Representative",
  "Business Development Manager",
  "Senior Business Development Manager",
  "Director of Business Development",
  "VP of Business Development",
  "Customer Success Manager",
  "Senior Customer Success Manager",
  "Director of Customer Success",
  "VP of Customer Success",
  "Solutions Engineer",
  "Senior Solutions Engineer",
  "Solutions Architect",
  "Pre-Sales Engineer",
  "Senior Pre-Sales Engineer",
  "Sales Engineer",
  "Senior Sales Engineer",
  "Sales Operations Manager",
  "Sales Operations Analyst",
  "Revenue Operations Manager",
  "Channel Manager",
  "Partner Manager",
  "Senior Partner Manager",
  "Partnerships Director",

  // ── Marketing ────────────────────────────────────────────────────────
  "Marketing Coordinator",
  "Marketing Associate",
  "Marketing Manager",
  "Senior Marketing Manager",
  "Marketing Director",
  "Senior Marketing Director",
  "VP of Marketing",
  "SVP of Marketing",
  "CMO",
  "Growth Manager",
  "Senior Growth Manager",
  "Head of Growth",
  "VP of Growth",
  "Growth Marketing Manager",
  "Content Marketing Manager",
  "Senior Content Marketing Manager",
  "Content Strategist",
  "Senior Content Strategist",
  "Content Writer",
  "Senior Content Writer",
  "Copywriter",
  "Senior Copywriter",
  "SEO Specialist",
  "Senior SEO Specialist",
  "SEO Manager",
  "SEM Specialist",
  "Digital Marketing Manager",
  "Senior Digital Marketing Manager",
  "Social Media Manager",
  "Senior Social Media Manager",
  "Social Media Specialist",
  "Performance Marketing Manager",
  "Senior Performance Marketing Manager",
  "Demand Generation Manager",
  "Senior Demand Generation Manager",
  "Brand Manager",
  "Senior Brand Manager",
  "Brand Director",
  "Communications Manager",
  "PR Manager",
  "Public Relations Specialist",
  "Marketing Analyst",
  "Marketing Operations Manager",
  "Email Marketing Manager",
  "Product Marketing Manager",
  "Senior Product Marketing Manager",
  "Director of Product Marketing",
  "VP of Product Marketing",
  "Event Manager",
  "Field Marketing Manager",
  "Community Manager",
  "Senior Community Manager",

  // ── HR / People ──────────────────────────────────────────────────────
  "HR Coordinator",
  "HR Generalist",
  "HR Manager",
  "Senior HR Manager",
  "HR Director",
  "VP of HR",
  "HR Business Partner",
  "Senior HR Business Partner",
  "Recruiter",
  "Senior Recruiter",
  "Technical Recruiter",
  "Senior Technical Recruiter",
  "Lead Recruiter",
  "Recruiting Manager",
  "Talent Acquisition Specialist",
  "Talent Acquisition Manager",
  "Senior Talent Acquisition Manager",
  "Director of Talent Acquisition",
  "Head of Talent Acquisition",
  "VP of Talent Acquisition",
  "People Operations Manager",
  "Senior People Operations Manager",
  "Head of People",
  "VP of People",
  "Chief People Officer",
  "Compensation Analyst",
  "Senior Compensation Analyst",
  "Compensation Manager",
  "Benefits Manager",
  "Total Rewards Manager",
  "Learning and Development Manager",
  "Training Manager",
  "Diversity and Inclusion Manager",
  "Employee Experience Manager",
  "HRIS Analyst",
  "People Analyst",
  "Workforce Planning Analyst",

  // ── Finance ──────────────────────────────────────────────────────────
  "Financial Analyst",
  "Senior Financial Analyst",
  "Finance Manager",
  "Senior Finance Manager",
  "Finance Director",
  "VP of Finance",
  "CFO",
  "Controller",
  "Assistant Controller",
  "Accounting Manager",
  "Senior Accounting Manager",
  "Staff Accountant",
  "Senior Accountant",
  "Tax Manager",
  "Senior Tax Manager",
  "Tax Analyst",
  "FP&A Analyst",
  "Senior FP&A Analyst",
  "FP&A Manager",
  "Director of FP&A",
  "Investment Analyst",
  "Senior Investment Analyst",
  "Portfolio Manager",
  "Treasury Analyst",
  "Treasury Manager",
  "Audit Manager",
  "Internal Auditor",
  "Revenue Accountant",
  "Accounts Payable Manager",
  "Accounts Receivable Manager",
  "Billing Analyst",
  "Payroll Manager",

  // ── Executive ────────────────────────────────────────────────────────
  "CEO",
  "CTO",
  "CFO",
  "COO",
  "CPO",
  "CMO",
  "CIO",
  "CISO",
  "Chief Revenue Officer",
  "Chief Data Officer",
  "Chief AI Officer",
  "Chief Strategy Officer",
  "Chief Growth Officer",
  "Chief People Officer",
  "Chief Legal Officer",
  "Chief Compliance Officer",
  "Chief Design Officer",
  "Chief Analytics Officer",
  "President",
  "Co-Founder",
  "Founder",
  "Managing Director",
  "Executive Vice President",
  "Senior Vice President",
  "Vice President",
  "General Manager",

  // ── Operations ───────────────────────────────────────────────────────
  "Operations Manager",
  "Senior Operations Manager",
  "Operations Director",
  "VP of Operations",
  "Chief Operating Officer",
  "Business Operations Manager",
  "Senior Business Operations Manager",
  "Business Operations Analyst",
  "Strategy and Operations Manager",
  "Supply Chain Manager",
  "Senior Supply Chain Manager",
  "Supply Chain Analyst",
  "Logistics Manager",
  "Senior Logistics Manager",
  "Logistics Coordinator",
  "Procurement Manager",
  "Senior Procurement Manager",
  "Vendor Manager",
  "Facilities Manager",
  "Office Manager",

  // ── Legal ────────────────────────────────────────────────────────────
  "General Counsel",
  "Associate General Counsel",
  "Corporate Counsel",
  "Senior Corporate Counsel",
  "Legal Counsel",
  "Senior Legal Counsel",
  "Legal Director",
  "VP of Legal",
  "Chief Legal Officer",
  "Compliance Officer",
  "Senior Compliance Officer",
  "Compliance Manager",
  "Compliance Director",
  "Paralegal",
  "Senior Paralegal",
  "Legal Operations Manager",
  "Contract Manager",
  "Contracts Administrator",
  "Privacy Counsel",
  "IP Counsel",
  "Employment Counsel",
  "Litigation Counsel",
  "Regulatory Affairs Manager",

  // ── Customer Support ─────────────────────────────────────────────────
  "Customer Support Specialist",
  "Senior Customer Support Specialist",
  "Customer Support Representative",
  "Technical Support Engineer",
  "Senior Technical Support Engineer",
  "Technical Support Specialist",
  "Support Manager",
  "Senior Support Manager",
  "Customer Support Manager",
  "Director of Customer Support",
  "VP of Customer Support",
  "Customer Experience Manager",
  "Senior Customer Experience Manager",
  "Director of Customer Experience",
  "Customer Service Representative",
  "Help Desk Analyst",
  "Help Desk Manager",
  "Implementation Specialist",
  "Onboarding Specialist",
  "Customer Onboarding Manager",
  "Technical Account Manager",
  "Senior Technical Account Manager",

  // ── Consulting ───────────────────────────────────────────────────────
  "Consultant",
  "Senior Consultant",
  "Principal Consultant",
  "Management Consultant",
  "Strategy Consultant",
  "Technology Consultant",
  "IT Consultant",
  "Business Consultant",

  // ── Education & Training ─────────────────────────────────────────────
  "Technical Writer",
  "Senior Technical Writer",
  "Lead Technical Writer",
  "Documentation Manager",
  "Technical Editor",
  "Instructional Designer",
  "Curriculum Developer",
  "Training Specialist",
];

export const JOB_TITLES: string[] = [...new Set(_RAW_JOB_TITLES)];

/**
 * Filters job titles by a search query.
 *
 * - Returns an empty array if query is fewer than 2 characters.
 * - Case-insensitive matching against any part of the title.
 * - Results are sorted so titles that START with the query appear first,
 *   followed by titles that merely contain the query.
 * - Returns at most 10 results.
 */
export function filterJobTitles(query: string): string[] {
  const trimmed = query.trim();
  if (trimmed.length < 2) {
    return [];
  }

  const lowerQuery = trimmed.toLowerCase();

  const startsWithMatches: string[] = [];
  const containsMatches: string[] = [];

  for (const title of JOB_TITLES) {
    const lowerTitle = title.toLowerCase();
    if (lowerTitle.startsWith(lowerQuery)) {
      startsWithMatches.push(title);
    } else if (lowerTitle.includes(lowerQuery)) {
      containsMatches.push(title);
    }
  }

  return [...startsWithMatches, ...containsMatches].slice(0, 10);
}
